inherit_from:
  - .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  Exclude:
    - 'bin/*'
    - 'config/**/*'
    - 'db/**/*'
  NewCops: enable
  TargetRubyVersion: 3.0

Rails:
  Enabled: true

# Configuration parameters: Max.
RSpec/ExampleLength:
  Max: 8