inherit_from:
  - .rubocop_todo.yml

plugins:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  Exclude:
    - "bin/*"
    - "config/**/*"
    - "db/**/*"
    - "vendor/**/*"
  NewCops: enable
  TargetRubyVersion: 3.4

Rails:
  Enabled: true

# Configuration parameters: Max.
RSpec/ExampleLength:
  Max: 8
