notifications:
  email: false

rvm:
  - 2.3.4 # deployed
  - 2.4.1

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false
language: ruby

before_install:
- export TZ=America/Los_Angeles
