super_admin_groups:
  - dlss:staff
site_admin_groups:
  - sul:library-hours-admins
pinned_library_slug: 'green'
EMAIL_TO: library-hours-feedback@lists.stanford.edu
GLOBAL_ALERT: <%= false %>

RECAPTCHA:
  SITE_KEY: 6Lc6BAAAAAAAAChqRbQZcn_yyyyyyyyyyyyyyyyy
  SECRET_KEY: 6Lc6BAAAAAAAAKN3DRm6VA_xxxxxxxxxxxxxxxxx

analytics_debug: true
