# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe SpreadsheetsController, type: :controller do
  before do
    allow(controller).to receive(:current_user).and_return(user)
  end

  let(:spreadsheet) do
    Spreadsheet.create! do |s|
      s.attachment.attach io: StringIO.new('x,y,z'), filename: 'x.csv', content_type: 'text/plain'
    end
  end

  describe 'with an anonymous user' do
    let(:user) { nil }

    it 'should deny access to #index' do
      expect { get :index }.to raise_error CanCan::AccessDenied
    end

    it 'should deny access to #show' do
      expect { get :show, params: { id: spreadsheet } }.to raise_error CanCan::AccessDenied
    end

    it 'should deny access to #new' do
      expect { get :new }.to raise_error CanCan::AccessDenied
    end

    it 'should deny access to #edit' do
      expect { get :edit, params: { id: spreadsheet } }.to raise_error CanCan::AccessDenied
    end

    it 'should deny access to #update' do
      expect { post :update, params: { id: spreadsheet } }.to raise_error CanCan::AccessDenied
    end

    it 'should deny access to #destroy' do
      expect { delete :destroy, params: { id: spreadsheet } }.to raise_error CanCan::AccessDenied
    end
  end

  let(:uploaded_file) do
    Rack::Test::UploadedFile.new(Rails.root + 'spec/support/spreadsheet_fixture.csv', 'text/plain')
  end

  # This should return the minimal set of attributes required to create a valid
  # Spreadsheet. As you add validations to Spreadsheet, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    { attachment: uploaded_file }
  end

  let(:invalid_attributes) do
    { x: 1 }
  end

  let(:user) { build(:superadmin_user) }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SpreadsheetsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe 'GET #index' do
    it 'assigns all spreadsheets as @spreadsheets' do
      spreadsheet
      get :index, params: {}, session: valid_session
      expect(assigns(:spreadsheets)).to eq([spreadsheet])
    end
  end

  describe 'GET #show' do
    it 'assigns the requested spreadsheet as @spreadsheet' do
      get :show, params: { id: spreadsheet.to_param }, session: valid_session
      expect(assigns(:spreadsheet)).to eq(spreadsheet)
    end
  end

  describe 'GET #new' do
    it 'assigns a new spreadsheet as @spreadsheet' do
      get :new, params: {}, session: valid_session
      expect(assigns(:spreadsheet)).to be_a_new(Spreadsheet)
    end
  end

  describe 'GET #edit' do
    it 'assigns the requested spreadsheet as @spreadsheet' do
      get :edit, params: { id: spreadsheet.to_param }, session: valid_session
      expect(assigns(:spreadsheet)).to eq(spreadsheet)
    end
  end

  describe 'POST #create' do
    context 'with valid params' do
      it 'creates a new Spreadsheet' do
        expect do
          post :create, params: { spreadsheet: valid_attributes }, session: valid_session
        end.to change(Spreadsheet, :count).by(1)
      end

      it 'assigns a newly created spreadsheet as @spreadsheet' do
        post :create, params: { spreadsheet: valid_attributes }, session: valid_session
        expect(assigns(:spreadsheet)).to be_a(Spreadsheet)
        expect(assigns(:spreadsheet)).to be_persisted
      end

      it 'redirects to the created spreadsheet' do
        post :create, params: { spreadsheet: valid_attributes }, session: valid_session
        expect(response).to redirect_to(Spreadsheet.last)
      end
    end

    context 'with invalid params' do
      it 'raises an error' do
        expect { post :create, params: { spreadsheet: invalid_attributes }, session: valid_session }
          .to raise_error ActionController::ParameterMissing
      end
    end
  end

  describe 'DELETE #destroy' do
    it 'destroys the requested spreadsheet' do
      spreadsheet

      expect do
        delete :destroy, params: { id: spreadsheet.to_param }, session: valid_session
      end.to change(Spreadsheet, :count).by(-1)
    end

    it 'redirects to the spreadsheets list' do
      delete :destroy, params: { id: spreadsheet.to_param }, session: valid_session
      expect(response).to redirect_to(spreadsheets_url)
    end
  end
end
